# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
#   push:
#     tags:
#       - '*' 
  workflow_dispatch:
    inputs:
      machine:
        description: 'Machine to run on'     
        required: true
        default: 'macos-latest'

jobs:
  build:

    runs-on: ${{ github.event.inputs.machine }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.0
      with:
        name: build -Pether=${{ secrets.ETHER_API }} -Pinfura=${{ secrets.INFURA_API }}
        path:
          build/bin
        if-no-files-found: 
          error
